// Generated by `npm run prayer:select` — do not hand-edit.
//
// Cities are chosen as the capital plus the most populous few per country,
// from GeoNames cities15000, and every one of them has been matched to a real
// Diyanet district. A city with no district never reaches this list, because
// the globe promises Diyanet times for every dot it draws.
//
// GeoNames also supplies what Diyanet does not publish: coordinates for the
// globe, and the IANA timezone the snapshot uses to derive each day's UTC
// offset.

import data from '../data/cities.json' with { type: 'json' }

export interface City {
  /** Display name. */
  n: string
  /** Latitude, degrees north. */
  la: number
  /** Longitude, degrees east. */
  lo: number
  /** IANA timezone, e.g. "Europe/Amsterdam". */
  tz: string
  iso2: string
  country: string
  pop: number
  /** Diyanet district id — the snapshot filename. */
  ilceID: string
  ilceUrl: string
  /** Diyanet UlkeID, retained for the live-API fallback. */
  u: number
  /** Province/SehirAdi, retained for the live-API fallback. */
  p?: string
  /** Candidate district names, retained for the live-API fallback. */
  d: string[]
}

export const CITIES: City[] = data as City[]
